# -*- coding: utf-8 -*-
"""RFP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkV1ZzmAdDzkwrzPGmlsOmE3alRmn1MO
"""

!pip install transformers

from google.colab import files
uploaded=files.upload() #Upload the txt file
filename=list(uploaded.keys())[0]
with open(filename, 'r') as f: # read file
    rfp_text = f.read()

print("RFP Content:\n", rfp_text)

info={}
for line in rfp_text.splitlines():
    if "Title:" in line:
        info["Title"] = line.split("Title:")[1].strip()
    elif "Deadline:" in line:
        info["Deadline"] = line.split("Deadline:")[1].strip()
    elif "Budget:" in line:
        info["Budget"] = line.split("Budget:")[1].strip()
    elif "Email:" in line:
        info["Email"] = line.split("Email:")[1].strip()

print("Extracted Info:", info)

from transformers import pipeline
#text generator
generator = pipeline("text-generation", model="gpt2")
prompt = f"""
Write a simple proposal based on this:
Title: {info.get("Title","")}
Scope: {info.get("Scope","")}
Budget: {info.get("Budget","")}
Deadline: {info.get("Deadline","")}
"""
#proposal generating
proposal = generator(prompt,max_length=200, do_sample=True)[0]["generated_text"]
print("Generated Proposal:\n", proposal)

